name: nightly

on:
  schedule:
    # 00:00 UTC every day
    - cron: '0 0 * * *' 
  workflow_dispatch:
    # Manual run


jobs:
  purge_previous_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      
      - name: Empty ftl-multiverse directory
        run: |
          rclone delete GoogleDrive:ftl-multiverse

  build:
    needs: purge_previous_packages

    runs-on: ubuntu-latest
    container: python:3.10
    strategy:
      matrix:
        language: [ko, fr, de, zh_Hans]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .

    - name: Cache .cache directory (used for packaging)
      uses: actions/cache@v3
      with:
        path: .cache
        key: ${{ hashFiles('mvloc.config.jsonc') }}

    - name: Build packages
      run: |
        mvloc batch-apply ${{ matrix.language }}
        mvloc package ${{ matrix.language }}

    - name: Upload XML files as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: xml-${{ matrix.language }}
        path: |
          output-${{ matrix.language }}/
          report.txt

    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}

    - name: Upload the mod to GDrive
      run: |
        rclone copy report.txt GoogleDrive:ftl-multiverse/batch-apply-report-${{ matrix.language }}.txt
        rclone copy packages GoogleDrive:ftl-multiverse

