name: nightly

on:
  schedule:
    # 00:00 UTC every day
    - cron: '0 0 * * *' 
  workflow_dispatch:
    # Manual run


jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10
    strategy:
      matrix:
        language: [ko, fr, de, zh_Hans]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .

    - name: Cache .cache directory (used for packaging)
      uses: actions/cache@v3
      with:
        path: .cache
        key: ${{ hashFiles('mvloc.config.jsonc') }}

    - name: Build packages
      run: |
        mvloc batch-apply ${{ matrix.language }}
        mvloc package ${{ matrix.language }}

    - name: Upload XML files
      uses: actions/upload-artifact@v3
      with:
        name: xml-${{ matrix.language }}
        path: |
          output-${{ matrix.language }}/
          report.txt

    - name: Upload the mod
      uses: actions/upload-artifact@v3
      with:
        name: full-${{ matrix.language }}
        path: |
          packages/*
